### ISSUE TITLE
Split big classes by context.

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#402]
Some new functionalities would be good to be put in new classes, like 
the WizardAutoPlay (may not grow) 
and Crafting/Recipes (this may grow a huge lot).

I dont know how to use `friend` class yet, may not be required tho.

If there is other subcontexts that could be split from bloated .cpp files, point it out :)

**Comment by fejoa** [comment]
My friend, perhaps you might be interested in [this IVAN variant](http://repo.or.cz/w/k8-i-v-a-n.git)?
The developer posted a thread on it here: https://attnam.com/topics/another-one-IVAN-fork?page=1

A lot of work was done to split the source files up, and there might be a few good working examples in here of useful code. This particular dev wishes to remain underground for various reasons, but is happy for his code to be reused. Worth a look : )

**Comment by iology** [comment]
Also good to make a keybinding system.

OT: That guy did a good feat. I like that commit message: bye-bye, autocrap and make; hello, jam! %-)

**Comment by AquariusPower** [comment]
> Also good to make a keybinding system.

as I remember, Ivan3D has it right?
I merged it initially but couldnt maintain the 3D engine to fix it further.
https://github.com/AquariusPower/ivan/tree/Ivan3Dpatch

**Comment by iology** [comment]
> https://github.com/AquariusPower/ivan/blob/6786fcd54eb8b308be358db58220f50236d9b1ce/Main/Source/command.cpp#L59

It has no UI yet, and doesn't resolve conflicts with look-mode commands and such.

**Comment by AquariusPower** [comment]
I see, I meant it as a quickstart :)
