### ISSUE TITLE
Interrupted crafting crash

### ISSUE THREAD

**Issue by red-kangaroo** [Attnam/ivan#610]
Reported [here](https://attnam.com/topics/Crafting-crash).

Trying to make ingots out of iron. The first attempt was interrupted (because I was starving and passed out) but I decided to continue processing my lumps for a bones file. I didn't "continue previous job" (if such an option exists) but went straight back to "melt ingot" (which, side note, is poorly phrased - makes it sound like we are taking ingots and melting them down, rather than melting lumps into ingots).

CTD with the following message:

```
this crafting was already suspended
'rc.IscanBeSuspended()=1; itToolID=0; itTool2ID=0, itSpawnCfg=2, itSpawnMatMainCfg=28674; itSpawnMatMainVol=250; itSpawnMatSecCfg=0; itSpawnMatSecVol=0; otSpawnCfg=0; otSpawnMatMainCfg=0; otSpawnMatMainVol=0; otSpawnMatSecCfg=0; otSpawnMatSecVol=0; fsItemSpawnSearchPrototype=; fsCraftInfo=melt an ingot (), started at Underwater Tunnel II; v2AnvilLocation=0,0; v2ForgeLocation=129,12; v2WorkbenchLocation=0,0; v2PlaceAt=0,0; v2PlayerCraftingAt=128,12;
```

Any ideas, @AquariusPower ?

**Comment by AquariusPower** [comment]
could be "melt (something) into an ingot"? hehe yep that needs fixing :>
on the code we would change the var value from "melt" to "melt into" I think?

> I didn't "continue previous job" (if such an option exists)

I think it will be there, so you can continue it,

> this crafting was already suspended

and would be a way to avoid the "crash" (it was actually an intentional ABORT() based on the message above).

> but went straight back to "melt ingot"

Based on what you did, it should not crash in that way... 
It should just create a new melt action, and later if you try to use the suspended one it would complain about missing ingredients and would fail but not ABORT().

Btw, what branch you used for this test? Despite I didn't change anything about it so I guess this test will ABORT() in all branches.

**Comment by red-kangaroo** [comment]
Not me, that was Ischaldirh on the forums. :) I'd think they were playing the latest release, so it might have already been fixed in your feature branch.

**Comment by AquariusPower** [comment]
the bug still happens on latest branch somefixes1234
follow exactly what he said
I used a lump of 1000cm3 and ingots of minimum volume (so we have time to suspend it by pressing any key)
if I try to start a new melt action with the same lump it will ABORT()  with that message!

**Comment by AquariusPower** [comment]
implemented and tested: at https://github.com/Attnam/ivan/pull/587 :>

**Comment by red-kangaroo** [comment]
Maybe related: [Linux crafting crash](https://attnam.com/topics/Linux-crafting-crash)
